{{- if and .Values.auth.apiToken (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eclipse-mat-service.fullname" . }}-auth
  labels:
    {{- include "eclipse-mat-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-token: {{ .Values.auth.apiToken | quote }}
{{- end }}
